---
- block:
    - name: "Create '{{ flavor.name }}' flavor"
      os_image:
        auth: "{{ osp_auth }}"
        validate_certs: no
        name: "{{ flavor.name }}"
        vcpus: "{{ flavor.vcpus }}"
        ram: "{{ flavor.ram }}"
        disk: "{{ flavor.disk }}"
        state: present

    - name: "Delete /tmp/workdir/{{ image.url | basename }}"
      file:
        path: "/tmp/workdir/{{ image.url | basename }}"
        state: absent

  when:
    - "image.url is defined"
