---
networks:
  - name: internal
    shared: false
    create_router: true
    subnets:
      - name: internal
        cidr: 192.168.128.0/24
        gateway_ip: 192.168.128.1
        allocation_pools:
          - start: 192.168.128.2
            end: 192.168.128.254
        routed: true

security_groups:
  - name: ssh
    rules:
      - name: ssh
        direction: ingress
        protocol: tcp
        port_range_min: 22
        port_range_max: 22
        remote_ip_prefix: 0.0.0.0/0
  - name: dhcp_server
    rules:
      - name: dhcp
        direction: ingress
        protocol: udp
        port_range_min: 67
        port_range_max: 67
        remote_ip_prefix: 192.168.128.0/24
  - name: tftp_server
    rules:
      - name: tftp
        direction: ingress
        protocol: udp
        port_range_min: 69
        port_range_max: 69
        remote_ip_prefix: 192.168.128.0/24
  - name: dns_server
    rules:
      - name: dns
        direction: ingress
        protocol: udp
        port_range_min: 53
        port_range_max: 53
        remote_ip_prefix: 192.168.128.0/24

instances:
  - name: "{{ guid }}-server-bastion"
    count: 1
    image: rhel-8.1
    flavor: rhmms-small
    ports:
      - network: internal
        mac_address: fa:16:3e:00:00:ff
        fixed_ips:
          - subnet: internal
            ip_address: 192.168.128.254
        floating_ip: true
        security_groups:
          - ssh
          - dns_server
          - tftp_server
          - dhcp_server
    public_dns: true
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
      - key: "ostype"
        value: "linux"
      - key: "instance_filter"
        value: "{{ env_type }}-{{ email }}"
    volumes:
      - size: 20
    yum_repos:
      - rhel-7-server-rpms
      - rhel-7-server-ansible-2.9-rpms
