---
env_type: migrate-from-vmware-to-red-hat-infrastructure
output_dir: /tmp/workdir              # Writable working scratch directory
email: migrate-from-vmware-to-red-hat-infrastructure@example.com
cloud_provider: osp
guid: imstorhi01
osp_cluster_dns_zone: red.osp.opentlc.com

