---
#CHANGEME
guid: testimslab                                         # Your Global UNIQUE Identifier

env_type: migrate-from-vmware-to-red-hat-infrastructure  # Name of config to deploy
cloud_provider: osp                                      # Which AgnosticD Cloud Provider to use

output_dir: /tmp/output_dir                              # Writable working scratch directory
email: name@example.com                                  # User info for notifications

repo_method: file

#CHANGEME or put in the secret
own_repo_path: http://admin.example.com/repos/version

# Cloud specfic settings - example given here for OSP

# The domain that you want to add DNS entries to
osp_cluster_dns_zone: blue.osp.opentlc.com

# The dynamic DNS server you will add entries to.
# NOTE: This is only applicable when {{ use_dynamic_dns}} is true
osp_cluster_dns_server: ddns01.opentlc.com
